version: "1.0.{build}"
image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019
branches:
  only:
    - master
init:
  - cmd: git config --global core.autocrlf true
install:
  - cmd: dotnet --version
  - cmd: dotnet tool install --global altcover.visualizer
  - cmd: cd aliyun-net-credentials-unit-tests/ && dotnet add package AltCover && cd ../
build_script:
  - cmd: dotnet restore && dotnet build 
test_script:
  # Dotnet Test
  - dotnet test aliyun-net-credentials-unit-tests/ /p:AltCover=true
on_finish:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
